inherit_from:
  - .rubocop_cff.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'cff.gemspec'

# Turn this off for certain files where we have extra documentation
# towards the end of the file, after a block of private methods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/cff/model.rb'
    - 'lib/cff/reference.rb'

# I think 'has_key?' looks better than 'key?'.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Turn this off for now.
Style/FrozenStringLiteralComment:
  Enabled: false

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
